### ISSUE TITLE
Feature Request: hex viewer

### ISSUE THREAD

**Issue by rppein** [Eugene-Mark/bigdata-file-viewer#6] opened 2020-05-11 15:09 UTC
I need to inspect a couple of parquet datasets containing binary data. So far, the viewer doesn't seem to have an integrated hex viewer or at least a way to export the binary fields into a plain file.

**Comment by Eugene-Mark** [comment] 2020-05-12 13:47
@rrpein, thanks for update. Could you please show us where can we download parquet datasets that containing binary data, it will be great if we can reproduce the issue from our side.

**Comment by sharpe5** [comment] 2020-05-12 14:06
As a workaround in the meantime, try using Python to export the binary data from Parquet form into something else that is viewable.

**Comment by rppein** [comment] 2020-06-15 08:28
Sorry, but I didn't get permission to forward the sample files.

**Comment by Eugene-Mark** [comment] 2020-12-05 15:22
@rppein Could you pls provide the link to download the sample files.

**Comment by Eugene-Mark** [comment] 2023-09-04 01:17
Close it since it's over years, will reopen it if the feature is in the roadmap.

**Closed by Eugene-Mark** 2023-09-04 01:17 UTC
Labels: enhancement
